
title: Tigrimp #Your awesome title
email: tigrimpy@gmail.com
description: > # this means to ignore newlines until "baseurl"
  math.robotics.ee.red pandas

baseurl: /blog/
url: https://tigrimp.github.io/blog # the base hostname & protocol for your site

permalink: /:year-:month/:title
timezone: 

favicon: /assets/img/favicon.ico

google_analytics: #UA—XXXXXXXX-X
disqus_shortname: #disqus shortname
cusdis:
    app_id: #your cusdis app_id

user:
  name: tigrmip
  pic: /assets/img/cat.jpg
  picAlt: "frog"
  job: idiot
  #aboutme: true 

exclude:
  - README.md
  - LICENSE
  - github

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
